name: CI

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '~24'
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '~24'
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run test --run

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '~24'
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run lint
